# GitHub Actions workflow to test, build, and publish a Python package to PyPI
# Triggered when a GitHub Release is published

name: Upload Python Package

on:
  release:
    types: [published]  # Run this workflow only when a new GitHub release is published

permissions:
  contents: read  # Allows the workflow to read repo contents

jobs:
  test-and-build:
    runs-on: ubuntu-latest  # Use latest Ubuntu runner

    strategy:
      matrix:
        python-version: ["3.8", "3.11"]  # Run the job for Python 3.8 and 3.11

    steps:
      # Step 1: Checkout the source code from GitHub
      - uses: actions/checkout@v4

      # Step 2: Set up the desired Python version from matrix
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies and tools needed for testing and building
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip           # Always upgrade pip
          pip install -r requirements.txt               # Install required packages from your project
          pip install build flake8 pytest               # Install tools for building, linting, and testing

      # Step 4: Lint your code using flake8 (checks for code quality)
      - name: Lint with flake8
        run: flake8 rl_swarm/                           # Update folder name if needed

      # Step 5: Run tests using pytest
      - name: Run tests with pytest
        run: pytest tests/                              # Run all tests inside the tests/ folder

      # Step 6: Build your package (creates .tar.gz and .whl in dist/)
      - name: Build release distributions
        run: python -m build

      # Step 7: Upload the build artifacts (dist/) so they can be used by the next job
      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists                           # Artifact name
          path: dist/                                   # Path to the built package files

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - test-and-build  # Only run this after test-and-build job is successful

    permissions:
      id-token: write  # Needed for trusted publishing without using a password

    environment:
      name: pypi
      url: https://pypi.org/project/rl-swarm/  # Display this link in the GitHub deployment status

    steps:
      # Step 1: Download the uploaded artifact (built packages)
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists                           # Must match the uploaded name
          path: dist/                                   # Download to dist/ folder

      # Step 2: Publish the packages to PyPI
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/                           # Directory where built distributions are located
